### ISSUE TITLE
oversized image

### ISSUE THREAD

**Issue by BoogieHasFun** [CGray1234/TropiTracker#6]
![firefox_fRHC1druCx](https://github.com/user-attachments/assets/07eb6ca8-fe2c-4a8b-a3b1-30eabc51dc01)
you might've forgotten to scale something, or maybe it's a bug

**Comment by CGray1234** [comment]
Thank you, I'll get that fixed.

**Comment by CGray1234** [comment]
Fixed in [7d9cb7e](https://github.com/CGray1234/TropiTracker/commit/7d9cb7e)
